import React, { useState, useEffect, useMemo } from 'react';
import type { Hero, LoreRelation } from '../../types/athanor';
import { HEROES_DATA } from '../../data/heroesData';
import { FACTIONS_DATA } from '../../data/factionsData';
import { heroCustomStore } from '../../utils/heroCustomStore';
import { relationCategoryStore, renderCategoryIcon } from '../../utils/relationCategoryStore';
import {
  Sparkles,
  Layers,
  BookOpen,
  ArrowRight,
  ArrowUpRight,
  RotateCcw,
  X,
  Compass
} from 'lucide-react';
import './HeroRelationsOrbitDiagram.css';

export interface ResolvedRelation extends LoreRelation {
  targetHero: Hero;
  isAutoGenerated: boolean;
}

interface HeroRelationsOrbitDiagramProps {
  hero: Hero;
  onSelectHero: (hero: Hero) => void;
}

export const HeroRelationsOrbitDiagram: React.FC<HeroRelationsOrbitDiagramProps> = ({
  hero,
  onSelectHero
}) => {
  const [viewMode, setViewMode] = useState<'orbit' | 'cards'>('orbit');
  const [selectedRelationType, setSelectedRelationType] = useState<string>('all');
  const [activeLoreModal, setActiveLoreModal] = useState<ResolvedRelation | null>(null);
  const [updateTick, setUpdateTick] = useState<number>(0);

  // Sync when hero or custom data is updated
  useEffect(() => {
    const handleUpdate = () => setUpdateTick((v) => v + 1);
    window.addEventListener('athanor-hero-updated', handleUpdate);
    window.addEventListener('athanor-categories-updated', handleUpdate);
    return () => {
      window.removeEventListener('athanor-hero-updated', handleUpdate);
      window.removeEventListener('athanor-categories-updated', handleUpdate);
    };
  }, []);

  const allHeroes = useMemo(() => {
    void updateTick;
    return heroCustomStore.getActiveHeroes(HEROES_DATA);
  }, [updateTick]);

  // Compute all effective relations for current hero (explicit + smart lore auto-resolver)
  const effectiveRelations = useMemo<ResolvedRelation[]>(() => {
    void updateTick;
    const explicit = heroCustomStore.getHeroRelations(hero.id);

    const mappedExplicit: ResolvedRelation[] = [];
    for (const rel of explicit) {
      const otherId = rel.sourceHeroId === hero.id ? rel.targetHeroId : rel.sourceHeroId;
      const otherHero = allHeroes.find((h) => h.id === otherId);
      if (otherHero) {
        mappedExplicit.push({
          ...rel,
          targetHero: otherHero,
          isAutoGenerated: false,
        });
      }
    }

    // Canonical order for Ilumia
    if (hero.id === 'ilumia') {
      const canonicalOrder = ['tulen', 'volkath', 'telannas', 'arthur', 'marja', 'lauriel', 'bright'];
      mappedExplicit.sort((a, b) => {
        const idxA = canonicalOrder.indexOf(a.targetHero.id);
        const idxB = canonicalOrder.indexOf(b.targetHero.id);
        if (idxA !== -1 && idxB !== -1) return idxA - idxB;
        if (idxA !== -1) return -1;
        if (idxB !== -1) return 1;
        return 0;
      });
    }

    const result: ResolvedRelation[] = [...mappedExplicit];
    const existingIds = new Set(result.map((r) => r.targetHero.id));

    // Fallback & supplement from relatedHeroIds so no hero shows (0)
    if (result.length < 5 && hero.relatedHeroIds && hero.relatedHeroIds.length > 0) {
      for (const rId of hero.relatedHeroIds) {
        if (rId === hero.id || existingIds.has(rId)) continue;
        const otherHero = allHeroes.find((h) => h.id === rId);
        if (!otherHero) continue;

        const isEnemy =
          (hero.factionId === 'lokheim' && (otherHero.factionId === 'veda' || otherHero.factionId === 'norman' || otherHero.factionId === 'afata')) ||
          (otherHero.factionId === 'lokheim' && (hero.factionId === 'veda' || hero.factionId === 'norman' || hero.factionId === 'afata'));

        let relType: 'enemy' | 'ally' | 'rival' | 'love' | 'mentor' = 'ally';
        let label = 'Hợp tác';
        let desc = '';

        if (isEnemy) {
          relType = 'enemy';
          label = 'Thù địch';
          desc = `${hero.name} và ${otherHero.name} đối đầu khốc liệt trên chiến tuyến giữa phe ${FACTIONS_DATA[hero.factionId]?.name || 'Ánh Sáng'} và ${FACTIONS_DATA[otherHero.factionId]?.name || 'Bóng Tối'}, trải qua vô số trận chiến định đoạt vận mệnh Athanor.`;
        } else if (hero.factionId === otherHero.factionId) {
          relType = 'ally';
          label = 'Đồng liêu';
          desc = `Cùng phụng sự tại ${FACTIONS_DATA[hero.factionId]?.name || 'vương triều'}, ${hero.name} và ${otherHero.name} là những đồng chí hướng kề vai sát cánh thi hành sứ mệnh bảo vệ bờ cõi.`;
        } else {
          relType = 'ally';
          label = 'Hợp tác';
          desc = `Liên minh chiến lược giữa ${FACTIONS_DATA[hero.factionId]?.name} và ${FACTIONS_DATA[otherHero.factionId]?.name}. ${hero.name} cùng ${otherHero.name} phối hợp tác chiến để duy trì trật tự và nền hòa bình Athanor.`;
        }

        result.push({
          id: `auto-${hero.id}-${otherHero.id}`,
          sourceHeroId: hero.id,
          targetHeroId: otherHero.id,
          relationType: relType,
          label,
          description: desc,
          targetHero: otherHero,
          isAutoGenerated: true,
        });
        existingIds.add(otherHero.id);
        if (result.length >= 6) break;
      }
    }

    if (selectedRelationType !== 'all') {
      return result.filter((r) => r.relationType === selectedRelationType);
    }

    return result;
  }, [hero, allHeroes, selectedRelationType, updateTick]);

  const getRelationColor = (type: string) => {
    return relationCategoryStore.getCategory(type).color;
  };

  const getRelationIcon = (type: string) => {
    const cat = relationCategoryStore.getCategory(type);
    return renderCategoryIcon(cat.iconName, 13, 'orbit-badge-icon');
  };

  const isRedRelation = (rel: { relationType: string; label: string }, color?: string): boolean => {
    if (rel.relationType === 'enemy') return true;
    const lower = (rel.label || '').toLowerCase();
    const redKeywords = ['thù', 'địch', 'hận', 'đối đầu', 'sát', 'phản', 'truy sát', 'trừng phạt', 'kình'];
    if (redKeywords.some((kw) => lower.includes(kw))) {
      return true;
    }
    if (color && color.startsWith('#') && color.length >= 7) {
      const r = parseInt(color.slice(1, 3), 16);
      const g = parseInt(color.slice(3, 5), 16);
      const b = parseInt(color.slice(5, 7), 16);
      if (r > 150 && r > g * 1.35 && r > b * 1.15) {
        return true;
      }
    }
    return false;
  };

  // Pre-calculated orbital coordinates for satellite nodes with organic diagonal/oblique trajectories
  // Coordinates in SVG viewBox: 760 x 560, center cx = 380, cy = 280
  const { orbitalNodes, isBipolar, redCount, blueCount } = useMemo(() => {
    const cx = 380;
    const cy = 280;
    const count = effectiveRelations.length;

    if (count === 0) {
      return { orbitalNodes: [], isBipolar: false, redCount: 0, blueCount: 0 };
    }

    const redRels: typeof effectiveRelations = [];
    const blueRels: typeof effectiveRelations = [];

    effectiveRelations.forEach((rel) => {
      const catColor = relationCategoryStore.getCategory(rel.relationType).color;
      if (isRedRelation(rel, catColor)) {
        redRels.push(rel);
      } else {
        blueRels.push(rel);
      }
    });

    const isBipolarMode = redRels.length > 0 && blueRels.length > 0;
    const STAGGERED_RADIUS_MULTS = [1.06, 0.94, 1.03, 0.96, 1.08, 0.92, 1.05, 0.95];

    // Left angles (North-West and South-West)
    const LEFT_DIAGONAL_PRESETS: Record<number, number[]> = {
      1: [-140],
      2: [-138, 138],
      3: [-144, 126, 154],
      4: [-150, -126, 126, 150],
      5: [-152, -132, 124, 146, 160],
      6: [-154, -136, -120, 122, 140, 158],
    };

    // Right angles (North-East and South-East)
    const RIGHT_DIAGONAL_PRESETS: Record<number, number[]> = {
      1: [-38],
      2: [-42, 42],
      3: [-52, -24, 42],
      4: [-54, -24, 24, 54],
      5: [-56, -34, 22, 44, 58],
      6: [-58, -38, -22, 22, 40, 58],
    };

    const getSideAngles = (n: number, isLeft: boolean): number[] => {
      const presets = isLeft ? LEFT_DIAGONAL_PRESETS : RIGHT_DIAGONAL_PRESETS;
      if (presets[n]) return presets[n];

      const angles: number[] = [];
      const half = Math.ceil(n / 2);
      const otherHalf = n - half;

      if (isLeft) {
        for (let i = 0; i < half; i++) {
          angles.push(-156 + ((156 - 120) / Math.max(1, half - 1)) * i);
        }
        for (let i = 0; i < otherHalf; i++) {
          angles.push(120 + ((156 - 120) / Math.max(1, otherHalf - 1)) * i);
        }
      } else {
        for (let i = 0; i < half; i++) {
          angles.push(-58 + ((58 - 22) / Math.max(1, half - 1)) * i);
        }
        for (let i = 0; i < otherHalf; i++) {
          angles.push(22 + ((58 - 22) / Math.max(1, otherHalf - 1)) * i);
        }
      }
      return angles;
    };

    const FULL_360_DIAGONAL_PRESETS: Record<number, number[]> = {
      1: [-38],
      2: [-42, 138],
      3: [-36, 46, 142],
      4: [-40, 42, 138, -142],
      5: [-52, -22, 42, 136, -132],
      6: [-56, -24, 38, 126, 154, -136],
    };

    interface PreparedNode {
      rel: typeof effectiveRelations[0];
      angleDeg: number;
      isRedSide: boolean;
    }

    const calculatedNodes: PreparedNode[] = [];

    if (isBipolarMode) {
      const redAngles = getSideAngles(redRels.length, true);
      const blueAngles = getSideAngles(blueRels.length, false);

      redRels.forEach((rel, idx) => {
        calculatedNodes.push({
          rel,
          angleDeg: redAngles[idx],
          isRedSide: true,
        });
      });

      blueRels.forEach((rel, idx) => {
        calculatedNodes.push({
          rel,
          angleDeg: blueAngles[idx],
          isRedSide: false,
        });
      });
    } else {
      effectiveRelations.forEach((rel, index) => {
        let angleDeg = 0;
        if (FULL_360_DIAGONAL_PRESETS[count]) {
          angleDeg = FULL_360_DIAGONAL_PRESETS[count][index];
        } else {
          const baseTilt = 32;
          let rawAngle = (baseTilt + (360 / count) * index) % 360;
          if (rawAngle > 180) rawAngle -= 360;

          if (Math.abs(rawAngle) < 18) {
            rawAngle += rawAngle >= 0 ? 18 : -18;
          } else if (Math.abs(rawAngle - 90) < 18) {
            rawAngle += rawAngle >= 90 ? 18 : -18;
          } else if (Math.abs(rawAngle - (-90)) < 18) {
            rawAngle += rawAngle >= -90 ? 18 : -18;
          } else if (Math.abs(Math.abs(rawAngle) - 180) < 18) {
            rawAngle += rawAngle >= 0 ? -18 : 18;
          }
          angleDeg = rawAngle;
        }
        calculatedNodes.push({
          rel,
          angleDeg,
          isRedSide: isRedRelation(rel, relationCategoryStore.getCategory(rel.relationType).color),
        });
      });
    }

    const nodes = calculatedNodes.map(({ rel, angleDeg, isRedSide }, index) => {
      const angleRad = (angleDeg * Math.PI) / 180;
      const rMult = STAGGERED_RADIUS_MULTS[index % STAGGERED_RADIUS_MULTS.length];

      const Rx = 232 * rMult;
      const Ry = 192 * rMult;

      const sx = cx + Rx * Math.cos(angleRad);
      const sy = cy + Ry * Math.sin(angleRad);

      const dx = sx - cx;
      const dy = sy - cy;
      const dist = Math.sqrt(dx * dx + dy * dy);
      const ux = dx / dist;
      const uy = dy / dist;

      const xStart = cx + 58 * ux;
      const yStart = cy + 58 * uy;
      const xEnd = sx - 38 * ux;
      const yEnd = sy - 38 * uy;

      const isRight = sx >= cx;
      const isEnemy = isRedSide;
      const isAlly = !isRedSide;
      const cat = relationCategoryStore.getCategory(rel.relationType);
      const color = isEnemy ? (cat.color.startsWith('#007') ? '#ef4444' : cat.color) : cat.color;

      return {
        rel,
        sx,
        sy,
        xStart,
        yStart,
        xEnd,
        yEnd,
        isRight,
        isEnemy,
        isAlly,
        color,
        angleDeg,
      };
    });

    return {
      orbitalNodes: nodes,
      isBipolar: isBipolarMode,
      redCount: redRels.length,
      blueCount: blueRels.length,
    };
  }, [effectiveRelations]);

  return (
    <div className="hero-relations-orbit-cluster">
      {/* Header bar with title, count, and view toggle */}
      <div className="hero-relations-orbit-header">
        <div className="relations-header-title-group">
          <h4 className="relations-header-text">
            <Compass size={16} style={{ color: '#0284c7' }} />
            <span>CÁC MỐI DUYÊN NỢ & QUAN HỆ CHIẾN SỰ</span>
          </h4>
          <span className="relations-count-badge">
            {effectiveRelations.length} MỐI QUAN HỆ
          </span>
        </div>

        {/* View Switcher: Orbital Map vs Card List */}
        <div className="orbit-view-mode-toggle">
          <button
            type="button"
            className={`orbit-view-btn ${viewMode === 'orbit' ? 'active' : ''}`}
            onClick={() => setViewMode('orbit')}
            title="Chế độ Bản Đồ Tỏa Tròn Liên Minh & Thù Địch"
          >
            <Sparkles size={13} />
            <span>BẢN ĐỒ TỎA TRÒN</span>
          </button>
          <button
            type="button"
            className={`orbit-view-btn ${viewMode === 'cards' ? 'active' : ''}`}
            onClick={() => setViewMode('cards')}
            title="Chế độ Thẻ Hồ Sơ Điển Tích"
          >
            <Layers size={13} />
            <span>THẺ HỒ SƠ</span>
          </button>
        </div>
      </div>

      {/* Empty State */}
      {effectiveRelations.length === 0 && (
        <div className="orbit-empty-box">
          <p className="orbit-empty-message">
            Chưa có ghi nhận mối duyên nợ chiến sự nào cho <strong>{hero.name}</strong> theo bộ lọc này.
          </p>
          {selectedRelationType !== 'all' && (
            <button
              type="button"
              className="orbit-modal-btn-secondary"
              onClick={() => setSelectedRelationType('all')}
            >
              <RotateCcw size={12} />
              <span>Xem Tất Cả Quan Hệ</span>
            </button>
          )}
        </div>
      )}

      {/* VIEW MODE 1: RADIAL CONSTELLATION ORBIT */}
      {effectiveRelations.length > 0 && viewMode === 'orbit' && (
        <div className="orbit-stage-wrapper">
          <div className="orbit-stage-container">
            {/* SVG Celestial Canvas: Astrolabe Concentric Rings and Laser Beams */}
            <svg
              className="orbit-svg-canvas"
              viewBox="0 0 760 560"
              preserveAspectRatio="xMidYMid meet"
            >
              <defs>
                {/* Glow filters */}
                <filter id="detail-glow-red" x="-20%" y="-20%" width="140%" height="140%">
                  <feDropShadow dx="0" dy="0" stdDeviation="4" floodColor="#ef4444" floodOpacity="0.9" />
                </filter>
                <filter id="detail-glow-blue" x="-20%" y="-20%" width="140%" height="140%">
                  <feDropShadow dx="0" dy="0" stdDeviation="4" floodColor="#38bdf8" floodOpacity="0.85" />
                </filter>
                <filter id="detail-glow-rose" x="-20%" y="-20%" width="140%" height="140%">
                  <feDropShadow dx="0" dy="0" stdDeviation="4" floodColor="#f43f5e" floodOpacity="0.85" />
                </filter>

                {/* Radial background glow */}
                <radialGradient id="detail-center-ambient-glow" cx="50%" cy="50%" r="50%">
                  <stop offset="0%" stopColor="#223366" stopOpacity="0.45" />
                  <stop offset="60%" stopColor="#151b36" stopOpacity="0.2" />
                  <stop offset="100%" stopColor="#0d1124" stopOpacity="0" />
                </radialGradient>
              </defs>

              {/* Ambient Center Glow */}
              <circle cx="380" cy="280" r="260" fill="url(#detail-center-ambient-glow)" />

              {/* Concentric Astrolabe Orbital Rings */}
              <circle cx="380" cy="280" r="75" className="astrolabe-ring ring-1" />
              <circle cx="380" cy="280" r="140" className="astrolabe-ring ring-2" />
              <circle cx="380" cy="280" r="215" className="astrolabe-ring ring-3 ring-satellite-orbit" />
              <circle cx="380" cy="280" r="285" className="astrolabe-ring ring-4" />
              <circle cx="380" cy="280" r="350" className="astrolabe-ring ring-5" />

              {/* Subtle Oblique / Diagonal Celestial Guide Rays */}
              <line x1="160" y1="100" x2="600" y2="460" className="astrolabe-axis" />
              <line x1="600" y1="100" x2="160" y2="460" className="astrolabe-axis" />
              <line x1="130" y1="180" x2="630" y2="380" className="astrolabe-axis" />
              <line x1="130" y1="380" x2="630" y2="180" className="astrolabe-axis" />

              {/* Bipolar Division Overlay when both Red & Blue exist */}
              {isBipolar && (
                <g className="bipolar-celestial-overlay">
                  <line
                    x1="380"
                    y1="32"
                    x2="380"
                    y2="528"
                    stroke="rgba(148, 163, 184, 0.09)"
                    strokeWidth="1.2"
                    strokeDasharray="4 8"
                  />
                  {/* Left Wing (Red) */}
                  <g transform="translate(145, 34)">
                    <rect
                      x="-8"
                      y="-14"
                      width="168"
                      height="22"
                      rx="11"
                      fill="rgba(239, 68, 68, 0.08)"
                      stroke="rgba(239, 68, 68, 0.28)"
                      strokeWidth="1"
                    />
                    <text
                      x="76"
                      y="0"
                      fill="#f87171"
                      fontSize="9.5"
                      fontFamily="var(--font-playfair, serif)"
                      letterSpacing="0.1em"
                      textAnchor="middle"
                      fontWeight="600"
                    >
                      ◀ ĐỐI ĐỊCH & TỬ THÙ ({redCount})
                    </text>
                  </g>

                  {/* Right Wing (Blue) */}
                  <g transform="translate(450, 34)">
                    <rect
                      x="-8"
                      y="-14"
                      width="168"
                      height="22"
                      rx="11"
                      fill="rgba(56, 189, 248, 0.08)"
                      stroke="rgba(56, 189, 248, 0.28)"
                      strokeWidth="1"
                    />
                    <text
                      x="76"
                      y="0"
                      fill="#38bdf8"
                      fontSize="9.5"
                      fontFamily="var(--font-playfair, serif)"
                      letterSpacing="0.1em"
                      textAnchor="middle"
                      fontWeight="600"
                    >
                      ĐỒNG MINH & TRI KỶ ({blueCount}) ▶
                    </text>
                  </g>
                </g>
              )}

              {/* Connecting Laser Beams to each Satellite */}
              {orbitalNodes.map(({ rel, xStart, yStart, xEnd, yEnd, isEnemy, color }) => {
                const filterId = isEnemy ? 'url(#detail-glow-red)' : 'url(#detail-glow-blue)';
                const midX = (xStart + xEnd) / 2;
                const midY = (yStart + yEnd) / 2;

                return (
                  <g key={`orbit-beam-${rel.id}`}>
                    {/* Outer soft glow line */}
                    <line
                      x1={xStart}
                      y1={yStart}
                      x2={xEnd}
                      y2={yEnd}
                      stroke={color}
                      strokeWidth="4"
                      strokeOpacity="0.35"
                      filter={filterId}
                    />
                    {/* Inner sharp laser beam */}
                    <line
                      x1={xStart}
                      y1={yStart}
                      x2={xEnd}
                      y2={yEnd}
                      stroke={color}
                      strokeWidth="2.5"
                      strokeOpacity="0.95"
                    />
                    {/* Midpoint energy pulse dot */}
                    <circle cx={midX} cy={midY} r="2.5" fill="#ffffff" opacity="0.85" />
                    {/* Terminal anchor dots */}
                    <circle cx={xStart} cy={yStart} r="3.5" fill={color} />
                    <circle cx={xEnd} cy={yEnd} r="3.5" fill={color} />
                  </g>
                );
              })}
            </svg>

            {/* Center Hero Node */}
            <div className="orbit-center-node">
              <div className="center-avatar-ring">
                <img
                  src={hero.avatarUrl}
                  alt={hero.name}
                  className="center-avatar-img"
                />
              </div>
              <div className="center-hero-badge">
                <span className="center-hero-name">{hero.name}</span>
              </div>
            </div>

            {/* Surrounding Satellite Nodes */}
            {orbitalNodes.map(({ rel, sx, sy, isRight, isEnemy, isAlly }) => {
              const leftPct = (sx / 760) * 100;
              const topPct = (sy / 560) * 100;

              return (
                <div
                  key={`sat-node-${rel.id}`}
                  className={`orbit-satellite-unit ${isRight ? 'side-right' : 'side-left'}`}
                  style={{
                    left: `${leftPct}%`,
                    top: `${topPct}%`,
                  }}
                >
                  {/* Satellite Avatar */}
                  <div
                    className={`satellite-avatar-frame ${isEnemy ? 'frame-enemy' : isAlly ? 'frame-ally' : 'frame-neutral'}`}
                    onClick={() => onSelectHero(rel.targetHero)}
                    title={`Nhấp để mở chi tiết hồ sơ ${rel.targetHero.name}`}
                  >
                    <img
                      src={rel.targetHero.avatarUrl}
                      alt={rel.targetHero.name}
                      className="satellite-avatar-img"
                    />
                    <span className="satellite-hover-name">{rel.targetHero.name}</span>
                  </div>

                  {/* Floating Relationship Badge (Pill with Speed Trail) */}
                  <div className={`orbit-relation-pill ${isEnemy ? 'pill-enemy' : 'pill-ally'} ${isRight ? 'align-right' : 'align-left'}`}>
                    {getRelationIcon(rel.relationType)}
                    <span className="orbit-pill-text">{rel.label}</span>
                    <span className="orbit-pill-trail" />
                  </div>

                  {/* Lore Story Book Button (📖) */}
                  <button
                    type="button"
                    className="orbit-book-btn"
                    onClick={(e) => {
                      e.stopPropagation();
                      setActiveLoreModal(rel);
                    }}
                    title={`Xem điển tích mối quan hệ giữa ${hero.name} & ${rel.targetHero.name}`}
                  >
                    <BookOpen size={14} className="book-icon" />
                  </button>
                </div>
              );
            })}
          </div>

          {/* Subtitle helper note */}
          <div className="orbit-instructions-bar">
            {isBipolar ? (
              <>
                <span className="orbit-tip-item">
                  <span className="tip-dot tip-dot-red" /> <strong>Cánh Trái (Đỏ):</strong> Quan hệ Thù địch, đối kháng ({redCount})
                </span>
                <span className="orbit-tip-item">
                  <span className="tip-dot tip-dot-blue" /> <strong>Cánh Phải (Xanh):</strong> Quan hệ Đồng minh, tri kỷ ({blueCount})
                </span>
              </>
            ) : (
              <span className="orbit-tip-item">
                <span
                  className="tip-dot"
                  style={{
                    background: effectiveRelations.some((r) => isRedRelation(r)) ? '#ef4444' : '#38bdf8',
                    boxShadow: effectiveRelations.some((r) => isRedRelation(r)) ? '0 0 8px #ef4444' : '0 0 8px #38bdf8'
                  }}
                />
                <strong>Chế độ Đồng Nhất:</strong> Tỏa tròn 360° theo các hướng xiên đa dạng ({effectiveRelations.length})
              </span>
            )}
            <span className="orbit-tip-item">
              <BookOpen size={12} style={{ display: 'inline', verticalAlign: 'middle', marginRight: '4px' }} />
              Bấm vào biểu tượng <strong>Quyển Sách</strong> để đọc điển tích sử thi hoặc nhấp avatar để chuyển tướng
            </span>
          </div>
        </div>
      )}

      {/* VIEW MODE 2: DOSSIER CARDS (Accessible list view) */}
      {effectiveRelations.length > 0 && viewMode === 'cards' && (
        <div className="orbit-cards-grid">
          {effectiveRelations.map((rel) => {
            const color = getRelationColor(rel.relationType);

            return (
              <div
                key={rel.id}
                className="orbit-dossier-card"
                style={{ borderColor: `${color}55` }}
              >
                <div className="orbit-card-top-tag">
                  <span className="orbit-badge-indicator" style={{ color: color, borderColor: color }}>
                    {rel.label}
                  </span>
                </div>

                {/* Bridge between heroes */}
                <div className="orbit-bridge-row">
                  <div className="orbit-bridge-hero-unit">
                    <img src={hero.avatarUrl} alt={hero.name} className="orbit-bridge-avatar" />
                    <span className="orbit-bridge-hero-name">{hero.name}</span>
                  </div>

                  <div className="orbit-bridge-hairline" style={{ backgroundColor: color }}>
                    <span className="orbit-bridge-pulse-dot" style={{ backgroundColor: color }} />
                  </div>

                  <div
                    className="orbit-bridge-hero-unit clickable"
                    onClick={() => onSelectHero(rel.targetHero)}
                    title="Nhấp để chuyển sang xem hồ sơ nhân vật này"
                  >
                    <img src={rel.targetHero.avatarUrl} alt={rel.targetHero.name} className="orbit-bridge-avatar" />
                    <span className="orbit-bridge-hero-name target-name">{rel.targetHero.name}</span>
                  </div>
                </div>

                <p className="orbit-narrative-quote">
                  {rel.description}
                </p>

                <div className="orbit-card-footer">
                  <button
                    type="button"
                    className="orbit-view-link"
                    onClick={() => onSelectHero(rel.targetHero)}
                  >
                    <span>Khám phá hồ sơ {rel.targetHero.name}</span>
                    <ArrowRight size={13} />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Interactive Lore Story Popover Modal (When 📖 Book Button is clicked) */}
      {activeLoreModal && (
        <div className="orbit-lore-modal-backdrop" onClick={() => setActiveLoreModal(null)}>
          <div className="orbit-lore-modal-box" onClick={(e) => e.stopPropagation()}>
            <div className="orbit-lore-modal-header">
              <div className="orbit-lore-modal-title-col">
                <span className="orbit-lore-modal-folio">ARCHIVE // ĐIỂN TÍCH SỬ THI CHIẾN BÁO</span>
                <h3 className="orbit-lore-modal-title">
                  {hero.name} <span className="orbit-lore-vs-span">VS</span> {activeLoreModal.targetHero.name}
                </h3>
              </div>
              <button
                type="button"
                className="orbit-lore-close-btn"
                onClick={() => setActiveLoreModal(null)}
                title="Đóng cửa sổ"
              >
                <X size={18} />
              </button>
            </div>

            {/* Matchup Duelists Banner */}
            <div className="orbit-matchup-banner">
              <div className="orbit-matchup-side">
                <img src={hero.avatarUrl} alt={hero.name} className="orbit-matchup-avatar" />
                <span className="orbit-matchup-name">{hero.name}</span>
                <span className="orbit-matchup-faction" style={{ color: FACTIONS_DATA[hero.factionId]?.color }}>
                  {FACTIONS_DATA[hero.factionId]?.name}
                </span>
              </div>

              <div className="orbit-matchup-bridge">
                <span
                  className={`orbit-matchup-pill ${
                    activeLoreModal.relationType === 'enemy' || activeLoreModal.label.includes('Thù')
                      ? 'pill-enemy'
                      : 'pill-ally'
                  }`}
                >
                  {getRelationIcon(activeLoreModal.relationType)}
                  {activeLoreModal.label}
                </span>
                <div className="orbit-matchup-connecting-line" />
              </div>

              <div
                className="orbit-matchup-side clickable"
                onClick={() => {
                  const target = activeLoreModal.targetHero;
                  setActiveLoreModal(null);
                  onSelectHero(target);
                }}
                title="Nhấp để chuyển hồ sơ sang vị tướng này"
              >
                <img
                  src={activeLoreModal.targetHero.avatarUrl}
                  alt={activeLoreModal.targetHero.name}
                  className="orbit-matchup-avatar"
                />
                <span className="orbit-matchup-name target-name">{activeLoreModal.targetHero.name}</span>
                <span
                  className="orbit-matchup-faction"
                  style={{ color: FACTIONS_DATA[activeLoreModal.targetHero.factionId]?.color }}
                >
                  {FACTIONS_DATA[activeLoreModal.targetHero.factionId]?.name}
                </span>
              </div>
            </div>

            {/* Story Narrative Box */}
            <div className="orbit-lore-narrative-block">
              <div className="orbit-narrative-tag">
                <BookOpen size={14} style={{ color: '#38bdf8' }} />
                <span>BIÊN NIÊN SỬ KÝ:</span>
              </div>
              <p className="orbit-lore-modal-text">
                {activeLoreModal.description}
              </p>
            </div>

            {/* Modal Actions */}
            <div className="orbit-lore-modal-footer">
              <button
                type="button"
                className="orbit-modal-btn-secondary"
                onClick={() => setActiveLoreModal(null)}
              >
                <span>Đóng</span>
              </button>

              <button
                type="button"
                className="orbit-modal-btn-primary"
                onClick={() => {
                  const target = activeLoreModal.targetHero;
                  setActiveLoreModal(null);
                  onSelectHero(target);
                }}
              >
                <span>Xem Chi Tiết {activeLoreModal.targetHero.name}</span>
                <ArrowUpRight size={14} />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
