import React, { useState, useEffect, useMemo } from 'react';
import type { Hero, LoreRelation } from '../../types/athanor';
import { HEROES_DATA } from '../../data/heroesData';
import { FACTIONS_DATA } from '../../data/factionsData';
import { heroCustomStore } from '../../utils/heroCustomStore';
import { 
  ArrowRight, 
  ArrowUpRight, 
  BookOpen, 
  X, 
  Sparkles, 
  Layers,
  RotateCcw,
  Search,
  Tag
} from 'lucide-react';
import { EditorialDropdown, type DropdownOption } from '../common/EditorialDropdown';
import { relationCategoryStore, renderCategoryIcon } from '../../utils/relationCategoryStore';
import { RelationCategoryModal } from '../ChampionSpotlight/RelationCategoryModal';
import type { RelationCategory } from '../../types/athanor';
import './LoreGraph.css';

interface LoreGraphProps {
  onSelectHero: (hero: Hero) => void;
}

export interface ResolvedRelation extends LoreRelation {
  targetHero: Hero;
  isAutoGenerated: boolean;
}

export const LoreGraph: React.FC<LoreGraphProps> = ({ onSelectHero }) => {
  const [selectedHeroId, setSelectedHeroId] = useState<string>('ilumia');
  const [selectedRelationType, setSelectedRelationType] = useState<string>('all');
  const [viewMode, setViewMode] = useState<'orbit' | 'cards'>('orbit');
  const [activeLoreModal, setActiveLoreModal] = useState<ResolvedRelation | null>(null);
  const [overrideTick, setOverrideTick] = useState<number>(0);

  // Category management state
  const [categories, setCategories] = useState<RelationCategory[]>(() =>
    relationCategoryStore.getCategories()
  );
  const [isCategoryModalOpen, setIsCategoryModalOpen] = useState<boolean>(false);

  useEffect(() => {
    const refreshCats = () => setCategories(relationCategoryStore.getCategories());
    window.addEventListener('athanor-categories-updated', refreshCats);
    return () => window.removeEventListener('athanor-categories-updated', refreshCats);
  }, []);

  // Registry list search, faction & role filters
  const [registrySearch, setRegistrySearch] = useState<string>('');

  const [registryFaction, setRegistryFaction] = useState<string>('all');
  const [registryRole, setRegistryRole] = useState<string>('all');

  useEffect(() => {
    const handleUpdate = () => setOverrideTick((v) => v + 1);
    window.addEventListener('athanor-hero-updated', handleUpdate);
    return () => window.removeEventListener('athanor-hero-updated', handleUpdate);
  }, []);

  const allHeroes = useMemo(() => {
    void overrideTick;
    return heroCustomStore.getActiveHeroes(HEROES_DATA);
  }, [overrideTick]);

  const factionOptions: DropdownOption<string>[] = useMemo(() => {
    const list: DropdownOption<string>[] = [
      {
        value: 'all',
        label: 'TẤT CẢ THẾ LỰC',
        badge: allHeroes.length,
      },
    ];
    Object.values(FACTIONS_DATA).forEach((faction) => {
      const count = allHeroes.filter((h) => h.factionId === faction.id).length;
      list.push({
        value: faction.id,
        label: faction.name,
        badge: count,
        color: faction.color,
      });
    });
    return list;
  }, [allHeroes]);

  const roleOptions: DropdownOption<string>[] = useMemo(() => {
    const roles = ['Đấu Sĩ', 'Pháp Sư', 'Xạ Thủ', 'Sát Thủ', 'Đỡ Đòn', 'Trợ Thủ'];
    return [
      { value: 'all', label: 'TẤT CẢ VAI TRÒ', badge: allHeroes.length },
      ...roles.map((r) => ({
        value: r,
        label: r,
        badge: allHeroes.filter((h) => h.role === r || h.secondaryRole === r).length,
      })),
    ];
  }, [allHeroes]);

  const filteredRegistryHeroes = useMemo(() => {
    return allHeroes.filter((hero) => {
      const matchSearch =
        registrySearch.trim() === '' ||
        hero.name.toLowerCase().includes(registrySearch.toLowerCase()) ||
        hero.title.toLowerCase().includes(registrySearch.toLowerCase());
      const matchFaction =
        registryFaction === 'all' || hero.factionId === registryFaction;
      const matchRole =
        registryRole === 'all' || hero.role === registryRole || hero.secondaryRole === registryRole;
      return matchSearch && matchFaction && matchRole;
    });
  }, [allHeroes, registrySearch, registryFaction, registryRole]);

  const selectedHero = useMemo(() => {
    return allHeroes.find((h) => h.id === selectedHeroId) || allHeroes[0];
  }, [allHeroes, selectedHeroId]);

  // Compute all effective relations for selectedHero (canonical explicit + smart lore auto-resolver)
  const effectiveRelations = useMemo<ResolvedRelation[]>(() => {
    const explicit = heroCustomStore.getHeroRelations(selectedHero.id);

    const mappedExplicit: ResolvedRelation[] = [];
    for (const rel of explicit) {
      const otherId = rel.sourceHeroId === selectedHero.id ? rel.targetHeroId : rel.sourceHeroId;
      const otherHero = allHeroes.find((h) => h.id === otherId);
      if (otherHero) {
        mappedExplicit.push({
          ...rel,
          targetHero: otherHero,
          isAutoGenerated: false,
        });
      }
    }

    // If Ilumia is selected, ensure the order matches the in-game constellation exactly:
    // Tulen (top), Volkath (top-right), Tel'Annas (bottom-right), Arthur (bottom), Marja (left)
    if (selectedHero.id === 'ilumia') {
      const canonicalOrder = ['tulen', 'volkath', 'telannas', 'arthur', 'marja', 'lauriel', 'bright'];
      mappedExplicit.sort((a, b) => {
        const idxA = canonicalOrder.indexOf(a.targetHero.id);
        const idxB = canonicalOrder.indexOf(b.targetHero.id);
        if (idxA !== -1 && idxB !== -1) return idxA - idxB;
        if (idxA !== -1) return -1;
        if (idxB !== -1) return 1;
        return 0;
      });
    }

    const result: ResolvedRelation[] = [...mappedExplicit];
    const existingIds = new Set(result.map((r) => r.targetHero.id));

    // Fallback & supplement from relatedHeroIds so no hero EVER shows (0)
    if (result.length < 5 && selectedHero.relatedHeroIds && selectedHero.relatedHeroIds.length > 0) {
      for (const rId of selectedHero.relatedHeroIds) {
        if (rId === selectedHero.id || existingIds.has(rId)) continue;
        const otherHero = allHeroes.find((h) => h.id === rId);
        if (!otherHero) continue;

        const isEnemy =
          (selectedHero.factionId === 'lokheim' && (otherHero.factionId === 'veda' || otherHero.factionId === 'norman' || otherHero.factionId === 'afata')) ||
          (otherHero.factionId === 'lokheim' && (selectedHero.factionId === 'veda' || selectedHero.factionId === 'norman' || selectedHero.factionId === 'afata'));

        let relType: 'enemy' | 'ally' | 'rival' | 'love' | 'mentor' = 'ally';
        let label = 'Hợp tác';
        let desc = '';

        if (isEnemy) {
          relType = 'enemy';
          label = 'Thù địch';
          desc = `${selectedHero.name} và ${otherHero.name} đối đầu khốc liệt trên chiến tuyến giữa phe ${FACTIONS_DATA[selectedHero.factionId]?.name || 'Ánh Sáng'} và ${FACTIONS_DATA[otherHero.factionId]?.name || 'Bóng Tối'}, trải qua vô số trận chiến định đoạt vận mệnh Athanor.`;
        } else if (selectedHero.factionId === otherHero.factionId) {
          relType = 'ally';
          label = 'Đồng liêu';
          desc = `Cùng phụng sự tại ${FACTIONS_DATA[selectedHero.factionId]?.name || 'vương triều'}, ${selectedHero.name} và ${otherHero.name} là những đồng chí hướng kề vai sát cánh thi hành sứ mệnh bảo vệ bờ cõi.`;
        } else {
          relType = 'ally';
          label = 'Hợp tác';
          desc = `Liên minh chiến lược giữa ${FACTIONS_DATA[selectedHero.factionId]?.name} và ${FACTIONS_DATA[otherHero.factionId]?.name}. ${selectedHero.name} cùng ${otherHero.name} phối hợp tác chiến để duy trì trật tự và nền hòa bình Athanor.`;
        }

        result.push({
          id: `auto-${selectedHero.id}-${otherHero.id}`,
          sourceHeroId: selectedHero.id,
          targetHeroId: otherHero.id,
          relationType: relType,
          label,
          description: desc,
          targetHero: otherHero,
          isAutoGenerated: true,
        });
        existingIds.add(otherHero.id);
        if (result.length >= 6) break;
      }
    }

    // Filter by relationType if specified
    if (selectedRelationType !== 'all') {
      return result.filter((r) => r.relationType === selectedRelationType);
    }

    return result;
  }, [selectedHero, allHeroes, selectedRelationType]);

  const getRelationColor = (type: string) => {
    return relationCategoryStore.getCategory(type).color;
  };

  const getRelationIcon = (type: string, _label?: string) => {
    const cat = relationCategoryStore.getCategory(type);
    return renderCategoryIcon(cat.iconName, 13, 'orbit-badge-icon');
  };

  // Helper kiểm tra một quan hệ thuộc nhóm Đỏ (Tử thù, thù địch, đối kháng, tông màu đỏ)
  const isRedRelation = (rel: { relationType: string; label: string }, color?: string): boolean => {
    if (rel.relationType === 'enemy') return true;
    const lower = (rel.label || '').toLowerCase();
    const redKeywords = ['thù', 'địch', 'hận', 'đối đầu', 'sát', 'phản', 'truy sát', 'trừng phạt', 'kình'];
    if (redKeywords.some((kw) => lower.includes(kw))) {
      return true;
    }
    if (color && color.startsWith('#') && color.length >= 7) {
      const r = parseInt(color.slice(1, 3), 16);
      const g = parseInt(color.slice(3, 5), 16);
      const b = parseInt(color.slice(5, 7), 16);
      if (r > 150 && r > g * 1.35 && r > b * 1.15) {
        return true;
      }
    }
    return false;
  };

  // Pre-calculated orbital coordinates for satellite nodes with organic diagonal/oblique trajectories
  // Coordinates in SVG viewBox: 760 x 560, center cx = 380, cy = 280
  const { orbitalNodes, isBipolar, redCount, blueCount } = useMemo(() => {
    const cx = 380;
    const cy = 280;
    const count = effectiveRelations.length;

    if (count === 0) {
      return { orbitalNodes: [], isBipolar: false, redCount: 0, blueCount: 0 };
    }

    // Phân loại nhóm Đỏ vs Xanh
    const redRels: typeof effectiveRelations = [];
    const blueRels: typeof effectiveRelations = [];

    effectiveRelations.forEach((rel) => {
      const catColor = relationCategoryStore.getCategory(rel.relationType).color;
      if (isRedRelation(rel, catColor)) {
        redRels.push(rel);
      } else {
        blueRels.push(rel);
      }
    });

    const isBipolarMode = redRels.length > 0 && blueRels.length > 0;

    // Bán kính so le tạo chiều sâu không gian đa dạng (staggered distance reaches)
    const STAGGERED_RADIUS_MULTS = [1.06, 0.94, 1.03, 0.96, 1.08, 0.92, 1.05, 0.95];

    // CẤU TRÚC 1: KHI CẢ 2 MÀU CÙNG TỒN TẠI (ĐỎ 1 BÊN - TRÁI/TÂY, XANH 1 BÊN - PHẢI/ĐÔNG)
    // Các góc cho bên ĐỎ (Trái / Tây: dải Tây Bắc và Tây Nam, tránh hoàn toàn trục ngang 180° và trục dọc)
    const LEFT_DIAGONAL_PRESETS: Record<number, number[]> = {
      1: [-140],                                      // 1 nhánh xiên Tây Bắc
      2: [-138, 138],                                 // 1 xiên Tây Bắc, 1 xiên Tây Nam
      3: [-144, 126, 154],                           // 1 xiên Tây Bắc, 2 xiên Tây Nam so le
      4: [-150, -126, 126, 150],                     // 2 xiên Tây Bắc, 2 xiên Tây Nam
      5: [-152, -132, 124, 146, 160],                // 5 nhánh phân tán hài hòa
      6: [-154, -136, -120, 122, 140, 158],          // 6 nhánh tỏa rộng
    };

    // Các góc cho bên XANH (Phải / Đông: dải Đông Bắc và Đông Nam, tránh hoàn toàn trục ngang 0° và trục dọc)
    const RIGHT_DIAGONAL_PRESETS: Record<number, number[]> = {
      1: [-38],                                       // 1 nhánh xiên Đông Bắc
      2: [-42, 42],                                   // 1 xiên Đông Bắc, 1 xiên Đông Nam
      3: [-52, -24, 42],                              // 2 xiên Đông Bắc, 1 xiên Đông Nam
      4: [-54, -24, 24, 54],                          // 2 xiên Đông Bắc, 2 xiên Đông Nam
      5: [-56, -34, 22, 44, 58],                      // 5 nhánh phân tán hài hòa
      6: [-58, -38, -22, 22, 40, 58],                 // 6 nhánh tỏa rộng
    };

    const getSideAngles = (n: number, isLeft: boolean): number[] => {
      const presets = isLeft ? LEFT_DIAGONAL_PRESETS : RIGHT_DIAGONAL_PRESETS;
      if (presets[n]) return presets[n];

      // Động cho N > 6:
      const angles: number[] = [];
      const half = Math.ceil(n / 2);
      const otherHalf = n - half;

      if (isLeft) {
        for (let i = 0; i < half; i++) {
          angles.push(-156 + ((156 - 120) / Math.max(1, half - 1)) * i);
        }
        for (let i = 0; i < otherHalf; i++) {
          angles.push(120 + ((156 - 120) / Math.max(1, otherHalf - 1)) * i);
        }
      } else {
        for (let i = 0; i < half; i++) {
          angles.push(-58 + ((58 - 22) / Math.max(1, half - 1)) * i);
        }
        for (let i = 0; i < otherHalf; i++) {
          angles.push(22 + ((58 - 22) / Math.max(1, otherHalf - 1)) * i);
        }
      }
      return angles;
    };

    // CẤU TRÚC 2: KHI CHỈ CÓ 1 MÀU (TỎA TRÒN 360° BÌNH THƯỜNG THEO CÁC HƯỚNG XIÊN)
    const FULL_360_DIAGONAL_PRESETS: Record<number, number[]> = {
      1: [-38],                                    // Hướng xiên trên - phải
      2: [-42, 138],                              // Hai hướng xiên đối xứng qua tâm
      3: [-36, 46, 142],                          // 3 hướng nghiêng phân bổ đa dạng
      4: [-40, 42, 138, -142],                    // Cấu trúc chữ X tỏa tròn 4 hướng xiên
      5: [-52, -22, 42, 136, -132],               // 5 hướng nghiêng bất đối xứng sinh động
      6: [-56, -24, 38, 126, 154, -136],          // 6 hướng xiên tỏa rộng
    };

    interface PreparedNode {
      rel: typeof effectiveRelations[0];
      angleDeg: number;
      isRedSide: boolean;
    }

    const calculatedNodes: PreparedNode[] = [];

    if (isBipolarMode) {
      // Đỏ dồn về bên Trái, Xanh dồn về bên Phải
      const redAngles = getSideAngles(redRels.length, true);
      const blueAngles = getSideAngles(blueRels.length, false);

      redRels.forEach((rel, idx) => {
        calculatedNodes.push({
          rel,
          angleDeg: redAngles[idx],
          isRedSide: true,
        });
      });

      blueRels.forEach((rel, idx) => {
        calculatedNodes.push({
          rel,
          angleDeg: blueAngles[idx],
          isRedSide: false,
        });
      });
    } else {
      // Chỉ có 1 màu: tỏa tròn bình thường 360°
      effectiveRelations.forEach((rel, index) => {
        let angleDeg = 0;
        if (FULL_360_DIAGONAL_PRESETS[count]) {
          angleDeg = FULL_360_DIAGONAL_PRESETS[count][index];
        } else {
          // Thuật toán động tạo hướng nghiêng/xiên cho bất kỳ số lượng N >= 7:
          const baseTilt = 32;
          let rawAngle = (baseTilt + (360 / count) * index) % 360;
          if (rawAngle > 180) rawAngle -= 360;

          // Đẩy xa khỏi các trục ngang (0°, 180°) và trục dọc (90°, -90°) tối thiểu 18°
          if (Math.abs(rawAngle) < 18) {
            rawAngle += rawAngle >= 0 ? 18 : -18;
          } else if (Math.abs(rawAngle - 90) < 18) {
            rawAngle += rawAngle >= 90 ? 18 : -18;
          } else if (Math.abs(rawAngle - (-90)) < 18) {
            rawAngle += rawAngle >= -90 ? 18 : -18;
          } else if (Math.abs(Math.abs(rawAngle) - 180) < 18) {
            rawAngle += rawAngle >= 0 ? -18 : 18;
          }
          angleDeg = rawAngle;
        }
        calculatedNodes.push({
          rel,
          angleDeg,
          isRedSide: isRedRelation(rel, relationCategoryStore.getCategory(rel.relationType).color),
        });
      });
    }

    // Biến đổi tọa độ hình học (coordinates math)
    const nodes = calculatedNodes.map(({ rel, angleDeg, isRedSide }, index) => {
      const angleRad = (angleDeg * Math.PI) / 180;
      const rMult = STAGGERED_RADIUS_MULTS[index % STAGGERED_RADIUS_MULTS.length];

      // Bán kính elip kết hợp hệ số so le
      const Rx = 232 * rMult;
      const Ry = 192 * rMult;

      const sx = cx + Rx * Math.cos(angleRad);
      const sy = cy + Ry * Math.sin(angleRad);

      // Vector từ tâm tới vệ tinh
      const dx = sx - cx;
      const dy = sy - cy;
      const dist = Math.sqrt(dx * dx + dy * dy);
      const ux = dx / dist;
      const uy = dy / dist;

      // Start on center circle perimeter (r = 58)
      const xStart = cx + 58 * ux;
      const yStart = cy + 58 * uy;

      // End on satellite circle perimeter (r = 38)
      const xEnd = sx - 38 * ux;
      const yEnd = sy - 38 * uy;

      const isRight = sx >= cx;
      const isEnemy = isRedSide;
      const isAlly = !isRedSide;
      const cat = relationCategoryStore.getCategory(rel.relationType);
      const color = isEnemy ? (cat.color.startsWith('#007') ? '#ef4444' : cat.color) : cat.color;

      return {
        rel,
        sx,
        sy,
        xStart,
        yStart,
        xEnd,
        yEnd,
        isRight,
        isEnemy,
        isAlly,
        color,
        angleDeg,
      };
    });

    return {
      orbitalNodes: nodes,
      isBipolar: isBipolarMode,
      redCount: redRels.length,
      blueCount: blueRels.length,
    };
  }, [effectiveRelations]);

  return (
    <div className="editorial-lore-page">
      {/* Minimalist Top Heading */}
      <div className="lore-editorial-header">
        <div className="lore-badge-row">
          <span className="lore-constellation-chip">
            BẢN ĐỒ QUAN HỆ TỎA TRÒN
          </span>
          <span className="lore-hero-focus-chip">
            Tâm điểm: {selectedHero.name}
          </span>
        </div>

        <h1 className="lore-editorial-title">
          Mạng Lưới Định Mệnh & Ân Oán Sử Thi
        </h1>
        <p className="lore-editorial-desc">
          Khám phá mạng lưới liên kết ân oán, liên minh, tri kỷ và truyền thừa giữa các vị tướng cõi Athanor.
        </p>

        {/* Dynamic Category Filter Pills */}
        <div className="editorial-nexus-filters">
          <button
            className={`nexus-filter-pill ${selectedRelationType === 'all' ? 'active' : ''}`}
            onClick={() => setSelectedRelationType('all')}
          >
            TẤT CẢ QUAN HỆ
          </button>
          {categories.map((cat) => {
            const isSelected = selectedRelationType === cat.id;
            return (
              <button
                key={cat.id}
                className={`nexus-filter-pill ${isSelected ? 'active' : ''}`}
                style={{
                  borderColor: isSelected ? cat.color : undefined,
                  color: isSelected ? cat.color : undefined,
                  background: isSelected ? `${cat.color}15` : undefined
                }}
                onClick={() => setSelectedRelationType(cat.id)}
              >
                {renderCategoryIcon(cat.iconName, 12)}
                <span>{cat.name.toUpperCase()}</span>
              </button>
            );
          })}

          <button
            type="button"
            className="nexus-category-manager-btn"
            onClick={() => setIsCategoryModalOpen(true)}
            title="Quản lý danh mục các loại quan hệ (thêm, sửa, đổi màu, xóa)"
          >
            <Tag size={12} />
            <span>QUẢN LÝ DANH MỤC ({categories.length})</span>
          </button>
        </div>

      </div>

      {/* Main Interactive Network View */}
      <div className="editorial-nexus-layout">
        {/* Left: Personages Registry List */}
        <div className="nexus-registry-sidebar editorial-frame">
          <div className="registry-header">
            <div className="registry-header-row">
              <span className="registry-folio-title">DANH SÁCH TÂM ĐIỂM</span>
              <span className="registry-count-pill">
                {filteredRegistryHeroes.length}/{allHeroes.length}
              </span>
            </div>

            {/* Quick Search */}
            <div className="registry-search-box">
              <Search size={13} className="registry-search-ico" />
              <input
                type="text"
                className="registry-search-input"
                placeholder="TÌM TƯỚNG TÂM ĐIỂM..."
                value={registrySearch}
                onChange={(e) => setRegistrySearch(e.target.value)}
              />
              {registrySearch && (
                <button
                  type="button"
                  className="registry-search-clear"
                  onClick={() => setRegistrySearch('')}
                  title="Xóa tìm kiếm"
                >
                  <X size={12} />
                </button>
              )}
            </div>

            {/* Faction & Role Filters */}
            <div className="registry-dropdowns-group">
              <EditorialDropdown
                options={factionOptions}
                value={registryFaction}
                onChange={(val) => setRegistryFaction(val)}
                placeholder="TẤT CẢ THẾ LỰC"
              />
              <EditorialDropdown
                options={roleOptions}
                value={registryRole}
                onChange={(val) => setRegistryRole(val)}
                placeholder="TẤT CẢ VAI TRÒ"
              />
            </div>
          </div>

          <div className="registry-scroll-list">
            {filteredRegistryHeroes.length === 0 ? (
              <div className="registry-empty-state">
                <p>Không có tướng nào phù hợp.</p>
              </div>
            ) : (
              filteredRegistryHeroes.map((hero, index) => {
                const faction = FACTIONS_DATA[hero.factionId];
                const isSelected = hero.id === selectedHeroId;
                const num = index < 9 ? `№ 0${index + 1}` : `№ ${index + 1}`;

                return (
                  <button
                    key={hero.id}
                    className={`registry-hero-item ${isSelected ? 'active' : ''}`}
                    onClick={() => setSelectedHeroId(hero.id)}
                  >
                    <span className="registry-item-no">{num}</span>
                    <img src={hero.avatarUrl} alt={hero.name} className="registry-thumb" />
                    <div className="registry-meta-col">
                      <span className="registry-name">{hero.name}</span>
                      <span className="registry-faction-name" style={{ color: faction?.color }}>
                        {faction?.name}
                      </span>
                    </div>
                  </button>
                );
              })
            )}
          </div>
        </div>

        {/* Right: Focused Hero Dossier & Orbital Constellation Board */}
        <div className="nexus-focus-board editorial-frame">
          {/* Focused Hero Masthead */}
          <div className="nexus-focus-masthead">
            <div className="focus-left-identity">
              <img src={selectedHero.avatarUrl} alt={selectedHero.name} className="focus-monogram-portrait" />
              <div className="focus-name-col">
                <div className="focus-tags-row">
                  <span className={`badge badge-${selectedHero.factionId}`}>
                    {FACTIONS_DATA[selectedHero.factionId]?.name}
                  </span>
                  <span className="badge badge-role">{selectedHero.role}</span>
                </div>
                <h2 className="focus-grand-title">
                  {selectedHero.name} <span className="focus-sub-epithet">「{selectedHero.title}」</span>
                </h2>
                <p className="focus-quote-line">“{selectedHero.quote}”</p>
              </div>
            </div>

            <button
              className="btn-secondary"
              onClick={() => onSelectHero(selectedHero)}
            >
              <span>HỒ SƠ TÁC CHIẾN</span>
              <ArrowUpRight size={14} />
            </button>
          </div>

          {/* Literary Overview */}
          <div className="nexus-story-overview">
            <div className="overview-header-tag">
              <span className="overview-no">CHRON. NOTE</span>
              <span className="overview-title">VỊ THẾ TRONG TRẬT TỰ ĐẠI LỤC ATHANOR:</span>
            </div>
            <p className="overview-text">{selectedHero.lore}</p>
          </div>

          {/* Intersecting Destinies Section with View Switcher */}
          <div className="nexus-relations-cluster">
            <div className="relations-header-line">
              <span className="relations-header-text">
                CÁC MỐI DUYÊN NỢ & QUAN HỆ CHIẾN SỰ ({effectiveRelations.length})
              </span>

              {/* View Switcher: Orbital Map vs Card List */}
              <div className="nexus-view-mode-toggle">
                <button
                  className={`view-mode-btn ${viewMode === 'orbit' ? 'active' : ''}`}
                  onClick={() => setViewMode('orbit')}
                  title="Chế độ Bản Đồ Tỏa Tròn Liên Minh & Thù Địch"
                >
                  <Sparkles size={13} />
                  <span>BẢN ĐỒ TỎA TRÒN</span>
                </button>
                <button
                  className={`view-mode-btn ${viewMode === 'cards' ? 'active' : ''}`}
                  onClick={() => setViewMode('cards')}
                  title="Chế độ Thẻ Hồ Sơ Điển Tích"
                >
                  <Layers size={13} />
                  <span>THẺ HỒ SƠ</span>
                </button>
              </div>
            </div>

            {/* Empty state if a specific filter has 0 results */}
            {effectiveRelations.length === 0 && (
              <div className="nexus-empty-box">
                <p className="nexus-empty-message">
                  Không tìm thấy mối quan hệ phù hợp với bộ lọc hiện tại của <strong>{selectedHero.name}</strong>.
                </p>
                <button
                  className="btn-secondary"
                  style={{ margin: '0 auto', fontSize: '0.75rem', padding: '6px 14px' }}
                  onClick={() => setSelectedRelationType('all')}
                >
                  <RotateCcw size={12} />
                  <span>Xem Tất Cả Quan Hệ</span>
                </button>
              </div>
            )}

            {/* VIEW MODE 1: RADIAL CONSTELLATION ORBIT (Matches user screenshot) */}
            {effectiveRelations.length > 0 && viewMode === 'orbit' && (
              <div className="orbit-stage-wrapper">
                <div className="orbit-stage-container">
                  {/* SVG Celestial Canvas: Astrolabe Concentric Rings and Laser Beams */}
                  <svg
                    className="orbit-svg-canvas"
                    viewBox="0 0 760 560"
                    preserveAspectRatio="xMidYMid meet"
                  >
                    <defs>
                      {/* Glow filters */}
                      <filter id="glow-red" x="-20%" y="-20%" width="140%" height="140%">
                        <feDropShadow dx="0" dy="0" stdDeviation="4" floodColor="#ef4444" floodOpacity="0.9" />
                      </filter>
                      <filter id="glow-blue" x="-20%" y="-20%" width="140%" height="140%">
                        <feDropShadow dx="0" dy="0" stdDeviation="4" floodColor="#38bdf8" floodOpacity="0.85" />
                      </filter>
                      <filter id="glow-rose" x="-20%" y="-20%" width="140%" height="140%">
                        <feDropShadow dx="0" dy="0" stdDeviation="4" floodColor="#f43f5e" floodOpacity="0.85" />
                      </filter>

                      {/* Radial background glow */}
                      <radialGradient id="center-ambient-glow" cx="50%" cy="50%" r="50%">
                        <stop offset="0%" stopColor="#223366" stopOpacity="0.45" />
                        <stop offset="60%" stopColor="#151b36" stopOpacity="0.2" />
                        <stop offset="100%" stopColor="#0d1124" stopOpacity="0" />
                      </radialGradient>
                    </defs>

                    {/* Ambient Center Glow */}
                    <circle cx="380" cy="280" r="260" fill="url(#center-ambient-glow)" />

                    {/* Concentric Astrolabe Orbital Rings */}
                    <circle cx="380" cy="280" r="75" className="astrolabe-ring ring-1" />
                    <circle cx="380" cy="280" r="140" className="astrolabe-ring ring-2" />
                    <circle cx="380" cy="280" r="215" className="astrolabe-ring ring-3 ring-satellite-orbit" />
                    <circle cx="380" cy="280" r="285" className="astrolabe-ring ring-4" />
                    <circle cx="380" cy="280" r="350" className="astrolabe-ring ring-5" />

                    {/* Subtle Oblique / Diagonal Celestial Guide Rays (Không dùng trục ngang X hay dọc Y) */}
                    <line x1="160" y1="100" x2="600" y2="460" className="astrolabe-axis" />
                    <line x1="600" y1="100" x2="160" y2="460" className="astrolabe-axis" />
                    <line x1="130" y1="180" x2="630" y2="380" className="astrolabe-axis" />
                    <line x1="130" y1="380" x2="630" y2="180" className="astrolabe-axis" />

                    {/* Phân cực Lưỡng Diện Chiến Tuyến (Khi có cả Đỏ và Xanh) */}
                    {isBipolar && (
                      <g className="bipolar-celestial-overlay">
                        {/* Trục ranh giới thẳng đứng mờ ảo giữa hai cực */}
                        <line
                          x1="380"
                          y1="32"
                          x2="380"
                          y2="528"
                          stroke="rgba(148, 163, 184, 0.09)"
                          strokeWidth="1.2"
                          strokeDasharray="4 8"
                        />
                        {/* Nhãn Cực Đỏ (Bên Trái) */}
                        <g transform="translate(145, 34)">
                          <rect
                            x="-8"
                            y="-14"
                            width="168"
                            height="22"
                            rx="11"
                            fill="rgba(239, 68, 68, 0.08)"
                            stroke="rgba(239, 68, 68, 0.28)"
                            strokeWidth="1"
                          />
                          <text
                            x="76"
                            y="0"
                            fill="#f87171"
                            fontSize="9.5"
                            fontFamily="var(--font-newsreader)"
                            letterSpacing="0.1em"
                            textAnchor="middle"
                            fontWeight="600"
                          >
                            ◀ ĐỐI ĐỊCH & TỬ THÙ ({redCount})
                          </text>
                        </g>

                        {/* Nhãn Cực Xanh (Bên Phải) */}
                        <g transform="translate(450, 34)">
                          <rect
                            x="-8"
                            y="-14"
                            width="168"
                            height="22"
                            rx="11"
                            fill="rgba(56, 189, 248, 0.08)"
                            stroke="rgba(56, 189, 248, 0.28)"
                            strokeWidth="1"
                          />
                          <text
                            x="76"
                            y="0"
                            fill="#38bdf8"
                            fontSize="9.5"
                            fontFamily="var(--font-newsreader)"
                            letterSpacing="0.1em"
                            textAnchor="middle"
                            fontWeight="600"
                          >
                            ĐỒNG MINH & TRI KỶ ({blueCount}) ▶
                          </text>
                        </g>
                      </g>
                    )}

                    {/* Connecting Laser Beams to each Satellite */}
                    {orbitalNodes.map(({ rel, xStart, yStart, xEnd, yEnd, isEnemy, color }) => {
                      const filterId = isEnemy ? 'url(#glow-red)' : 'url(#glow-blue)';
                      const midX = (xStart + xEnd) / 2;
                      const midY = (yStart + yEnd) / 2;

                      return (
                        <g key={`beam-${rel.id}`}>
                          {/* Outer soft glow line */}
                          <line
                            x1={xStart}
                            y1={yStart}
                            x2={xEnd}
                            y2={yEnd}
                            stroke={color}
                            strokeWidth="4"
                            strokeOpacity="0.35"
                            filter={filterId}
                          />
                          {/* Inner sharp laser beam */}
                          <line
                            x1={xStart}
                            y1={yStart}
                            x2={xEnd}
                            y2={yEnd}
                            stroke={color}
                            strokeWidth="2.5"
                            strokeOpacity="0.95"
                          />
                          {/* Midpoint energy pulse dot */}
                          <circle cx={midX} cy={midY} r="2.5" fill="#ffffff" opacity="0.85" />
                          {/* Terminal anchor dots */}
                          <circle cx={xStart} cy={yStart} r="3.5" fill={color} />
                          <circle cx={xEnd} cy={yEnd} r="3.5" fill={color} />
                        </g>
                      );
                    })}
                  </svg>

                  {/* HTML Overlay Nodes (Responsive math matching viewBox 760 x 560) */}

                  {/* 1. Center Hero Node (Selected Hero) */}
                  <div className="orbit-center-node">
                    <div className="center-avatar-ring">
                      <img
                        src={selectedHero.avatarUrl}
                        alt={selectedHero.name}
                        className="center-avatar-img"
                      />
                    </div>
                    <div className="center-hero-badge">
                      <span className="center-hero-name">{selectedHero.name}</span>
                    </div>
                  </div>

                  {/* 2. Surrounding Satellite Nodes */}
                  {orbitalNodes.map(({ rel, sx, sy, isRight, isEnemy, isAlly }) => {
                    const leftPct = (sx / 760) * 100;
                    const topPct = (sy / 560) * 100;

                    return (
                      <div
                        key={`sat-node-${rel.id}`}
                        className={`orbit-satellite-unit ${isRight ? 'side-right' : 'side-left'}`}
                        style={{
                          left: `${leftPct}%`,
                          top: `${topPct}%`,
                        }}
                      >
                        {/* Satellite Avatar */}
                        <div
                          className={`satellite-avatar-frame ${isEnemy ? 'frame-enemy' : isAlly ? 'frame-ally' : 'frame-neutral'}`}
                          onClick={() => setSelectedHeroId(rel.targetHero.id)}
                          title={`Nhấp để đổi tâm điểm mạng lưới sang ${rel.targetHero.name}`}
                        >
                          <img
                            src={rel.targetHero.avatarUrl}
                            alt={rel.targetHero.name}
                            className="satellite-avatar-img"
                          />
                          <span className="satellite-hover-name">{rel.targetHero.name}</span>
                        </div>

                        {/* Floating Relationship Badge (Pill with Speed Trail) */}
                        <div className={`orbit-relation-pill ${isEnemy ? 'pill-enemy' : 'pill-ally'} ${isRight ? 'align-right' : 'align-left'}`}>
                          {getRelationIcon(rel.relationType, rel.label)}
                          <span className="orbit-pill-text">{rel.label}</span>
                          <span className="orbit-pill-trail" />
                        </div>

                        {/* Lore Story Book Button (📖) */}
                        <button
                          className="orbit-book-btn"
                          onClick={(e) => {
                            e.stopPropagation();
                            setActiveLoreModal(rel);
                          }}
                          title={`Xem điển tích mối quan hệ giữa ${selectedHero.name} & ${rel.targetHero.name}`}
                        >
                          <BookOpen size={14} className="book-icon" />
                        </button>
                      </div>
                    );
                  })}
                </div>

                {/* Subtitle helper note */}
                <div className="orbit-instructions-bar">
                  {isBipolar ? (
                    <>
                      <span className="orbit-tip-item">
                        <span className="tip-dot tip-dot-red" /> <strong>Cánh Trái (Đỏ):</strong> Quan hệ Thù địch, đối kháng ({redCount})
                      </span>
                      <span className="orbit-tip-item">
                        <span className="tip-dot tip-dot-blue" /> <strong>Cánh Phải (Xanh):</strong> Quan hệ Đồng minh, tri kỷ ({blueCount})
                      </span>
                    </>
                  ) : (
                    <span className="orbit-tip-item">
                      <span
                        className="tip-dot"
                        style={{
                          background: effectiveRelations.some((r) => isRedRelation(r)) ? '#ef4444' : '#38bdf8',
                          boxShadow: effectiveRelations.some((r) => isRedRelation(r)) ? '0 0 8px #ef4444' : '0 0 8px #38bdf8'
                        }}
                      />
                      <strong>Chế độ Đồng Nhất:</strong> Tỏa tròn 360° theo các hướng xiên đa dạng ({effectiveRelations.length})
                    </span>
                  )}
                  <span className="orbit-tip-item">
                    <BookOpen size={12} style={{ display: 'inline', verticalAlign: 'middle', marginRight: '4px' }} />
                    Bấm vào biểu tượng <strong>Quyển Sách</strong> để đọc điển tích sử thi
                  </span>
                </div>
              </div>
            )}

            {/* VIEW MODE 2: DOSSIER CARDS (Accessible list view) */}
            {effectiveRelations.length > 0 && viewMode === 'cards' && (
              <div className="nexus-cards-grid">
                {effectiveRelations.map((rel) => {
                  const color = getRelationColor(rel.relationType);

                  return (
                    <div
                      key={rel.id}
                      className="nexus-link-card"
                      style={{ borderColor: `${color}55` }}
                    >
                      <div className="nexus-card-top-tag">
                        <span className="nexus-badge-indicator" style={{ color: color, borderColor: color }}>
                          {rel.label}
                        </span>
                      </div>

                      {/* Bridge between heroes */}
                      <div className="nexus-bridge-row">
                        <div className="bridge-hero-unit">
                          <img src={selectedHero.avatarUrl} alt={selectedHero.name} className="bridge-avatar" />
                          <span className="bridge-hero-name">{selectedHero.name}</span>
                        </div>

                        <div className="bridge-hairline-connector" style={{ backgroundColor: color }}>
                          <span className="bridge-pulse-dot" style={{ backgroundColor: color }} />
                        </div>

                        <div
                          className="bridge-hero-unit clickable"
                          onClick={() => setSelectedHeroId(rel.targetHero.id)}
                          title="Nhấp để chuyển tâm điểm sang nhân vật này"
                        >
                          <img src={rel.targetHero.avatarUrl} alt={rel.targetHero.name} className="bridge-avatar" />
                          <span className="bridge-hero-name target-name">{rel.targetHero.name}</span>
                        </div>
                      </div>

                      <p className="nexus-narrative-quote">
                        {rel.description}
                      </p>

                      <div className="nexus-card-footer">
                        <button
                          className="nexus-view-link"
                          onClick={() => onSelectHero(rel.targetHero)}
                        >
                          <span>Hồ sơ {rel.targetHero.name}</span>
                          <ArrowRight size={13} />
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Interactive Lore Story Popover Modal (When 📖 Book Button is clicked) */}
      {activeLoreModal && (
        <div className="lore-modal-backdrop" onClick={() => setActiveLoreModal(null)}>
          <div className="lore-modal-box editorial-frame" onClick={(e) => e.stopPropagation()}>
            <div className="lore-modal-header">
              <div className="lore-modal-title-col">
                <span className="lore-modal-folio text-cerulean">ARCHIVE // ĐIỂN TÍCH SỬ THI CHIẾN BÁO</span>
                <h3 className="lore-modal-title">
                  {selectedHero.name} <span className="lore-vs-span">VS</span> {activeLoreModal.targetHero.name}
                </h3>
              </div>
              <button className="lore-modal-close-btn" onClick={() => setActiveLoreModal(null)}>
                <X size={18} />
              </button>
            </div>

            {/* Matchup Duelists Banner */}
            <div className="lore-matchup-banner">
              <div className="matchup-side left-side">
                <img src={selectedHero.avatarUrl} alt={selectedHero.name} className="matchup-avatar" />
                <span className="matchup-name">{selectedHero.name}</span>
                <span className="matchup-faction" style={{ color: FACTIONS_DATA[selectedHero.factionId]?.color }}>
                  {FACTIONS_DATA[selectedHero.factionId]?.name}
                </span>
              </div>

              <div className="matchup-center-bridge">
                <span
                  className={`matchup-relation-pill ${
                    activeLoreModal.relationType === 'enemy' || activeLoreModal.label.includes('Thù')
                      ? 'matchup-pill-enemy'
                      : 'matchup-pill-ally'
                  }`}
                >
                  {getRelationIcon(activeLoreModal.relationType, activeLoreModal.label)}
                  {activeLoreModal.label}
                </span>
                <div className="matchup-connecting-line" />
              </div>

              <div
                className="matchup-side right-side clickable"
                onClick={() => {
                  setSelectedHeroId(activeLoreModal.targetHero.id);
                  setActiveLoreModal(null);
                }}
                title="Nhấp để đổi tâm điểm"
              >
                <img src={activeLoreModal.targetHero.avatarUrl} alt={activeLoreModal.targetHero.name} className="matchup-avatar" />
                <span className="matchup-name target-name">{activeLoreModal.targetHero.name}</span>
                <span className="matchup-faction" style={{ color: FACTIONS_DATA[activeLoreModal.targetHero.factionId]?.color }}>
                  {FACTIONS_DATA[activeLoreModal.targetHero.factionId]?.name}
                </span>
              </div>
            </div>

            {/* Story Narrative Box */}
            <div className="lore-modal-narrative-block">
              <div className="narrative-tag">
                <BookOpen size={14} className="text-cerulean" />
                <span>BIÊN NIÊN SỬ KÝ:</span>
              </div>
              <p className="lore-modal-text">
                {activeLoreModal.description}
              </p>
            </div>

            {/* Modal Actions */}
            <div className="lore-modal-footer">
              <button
                className="btn-secondary"
                onClick={() => {
                  const target = activeLoreModal.targetHero;
                  setActiveLoreModal(null);
                  onSelectHero(target);
                }}
              >
                <span>Xem Hồ Sơ {activeLoreModal.targetHero.name}</span>
                <ArrowUpRight size={14} />
              </button>

              <button
                className="btn-primary"
                onClick={() => {
                  setSelectedHeroId(activeLoreModal.targetHero.id);
                  setActiveLoreModal(null);
                }}
              >
                <span>Chuyển Tâm Điểm Mạng Lưới</span>
                <ArrowRight size={14} />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Category Management Submodal */}
      <RelationCategoryModal
        isOpen={isCategoryModalOpen}
        onClose={() => setIsCategoryModalOpen(false)}
      />
    </div>
  );
};

